=== ClouGence/open-cdm/clouddm-platform/cgdm-console/src/main/resources/dm/rules/sec-rules.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT ruleSet ((queryRules?,sensitiveRules?) |EMPTY) >

<!ELEMENT queryRules (ruleDef*|EMPTY) >

<!ELEMENT sensitiveRules (ruleDef*|EMPTY) >

<!ELEMENT ruleDef (#PCDATA | EMPTY)*>
<!ATTLIST ruleDef
        id CDATA #REQUIRED
        ruleName CDATA #REQUIRED
        ruleDesc CDATA #REQUIRED
        scriptType CDATA #REQUIRED
        ruleTarget CDATA #IMPLIED
        senMode CDATA #IMPLIED
        oldId CDATA #IMPLIED
        deprecated (true|false) #IMPLIED
>

=== ClouGence/open-cdm/clouddm-platform/cgdm-console/src/main/resources/dm/rules/sec-rules.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ruleSet PUBLIC "-//clougence.com/sec-rules//DTD SecRule 1.0//EN" "classpath://dm/rules/sec-rules.dtd">
<ruleSet>
    <queryRules>
        <!-- catalog -->
        <ruleDef id="rule_catalog_001" ruleName="i18n::DEPRECATED_RULE_N_CATALOG_CHARACTER_SET" ruleDesc="i18n::DEPRECATED_RULE_D_CATALOG_CHARACTER_SET" ruleTarget="Catalog" scriptType="DetectRules" oldId="2" deprecated="true"><![CDATA[
#define "require" as bool
        default "true"
        enum ["true", "false"]
        hint "强制要求设置字符集"
#define "character_set" as string
        default "utf8mb4"
        enum ["utf8", "utf8mb4"]
        hint "允许使用的字符集"

// 对于 alert 语句，只有当设置了 character set 选项时候才进行校验
if
  @domain.sqlType in ['ALERT_CATALOG'] and
  @func.string.isNotBlank(@domain.characterSet)
then

    if @func.string.isBlank(#{character_set}) then
      return false //规则配置错误
    else
      return @func.string.equalsIgnoreCase(@domain.characterSet, #{character_set})
    end

end

// 对于 create 语句，检测是否必须设置 character set 选项
if @domain.sqlType == 'CREATE_CATALOG' then

  if cast(#{require} as bool) then

    if @func.string.isBlank(#{character_set}) then
      return false //规则配置错误
    else
      return @func.string.equalsIgnoreCase(@domain.characterSet, #{character_set})
    end

  else

    if @func.string.isBlank(@domain.characterSet) then
      return true
    else
      return @func.string.equalsIgnoreCase(@domain.characterSet, #{character_set})
    end

  end

end
]]></ruleDef>
        <ruleDef id="rule_catalog_002" ruleName="i18n::DEPRECATED_RULE_N_CATALOG_COLLATE" ruleDesc="i18n::DEPRECATED_RULE_D_CATALOG_COLLATE" ruleTarget="Catalog" scriptType="DetectRules" oldId="1" deprecated="true"><![CDATA[
#define "require" as bool
        default "true"
        enum ["true", "false"]
        hint "强制要求设置排序规则"
#define "collate" as string
        default "utf8mb4_unicode_ci"
        enum ["utf8_unicode_ci", "utf8mb4_unicode_ci"]
        hint "允许使用的排序规则"

// 对于 alert 语句，只有当设置了 collate 选项时候才进行校验
if
  @domain.sqlType in ['ALERT_CATALOG'] and
  @func.string.isNotBlank(@domain.collate)
then

    if @func.string.isBlank(#{collate}) then
      return false //规则配置错误
    else
      return @func.string.equalsIgnoreCase(@domain.collate, #{collate})
    end

end

// 对于 create 语句，检测是否必须设置 collate 选项
if @domain.sqlType == 'CREATE_CATALOG' then

  if cast(#{require} as bool) then

    if @func.string.isBlank(#{collate}) then
      return false //规则配置错误
    else
      return @func.string.equalsIgnoreCase(@domain.collate, #{collate})
    end

  else

    if @func.string.isBlank(@domain.collate) then
      return true
    else
      return @func.string.equalsIgnoreCase(@domain.collate, #{collate})
    end

  end

end
]]></ruleDef>
        <ruleDef id="rule_catalog_003" ruleName="i18n::RULE_N_CATALOG_NAME_CASE_TYPE" ruleDesc="i18n::RULE_D_CATALOG_NAME_CASE_TYPE" ruleTarget="Catalog" scriptType="DetectRules"><![CDATA[
#define "caseType" as string
        default "Lower case"
        enum ["Lower case", "Upper case", "Lower camel case", "Upper camel case"]
        hint "名称拼写规则"

if @domain.sqlType == 'CREATE_CATALOG' then
  checkName = @domain.catalog
elseif @domain.sqlType == 'RENAME_CATALOG' then
  checkName = @domain.newName
else
  return true
end

// ref document https://newbedev.com/regex-for-pascalcased-words-aka-camelcased-with-leading-uppercase-letter

if #{caseType} == 'Lower case' then
  return @func.string.lowerCase(checkName) == checkName

elseif #{caseType} == 'Upper case' then

  return @func.string.upperCase(checkName) == checkName

elseif #{caseType} == 'Lower camel case' then
  return checkName matches '[a-z]+((\d)|([A-Z0-9][a-z0-9]+))*([A-Z])?'

elseif #{caseType} == 'Upper camel case' then
  return checkName matches '([A-Z][a-z0-9]+)((\d)|([A-Z0-9][a-z0-9]+))*([A-Z])?'

else

  return false
end
]]></ruleDef>

        <!-- schema -->
        <ruleDef id="rule_schema_001" ruleName="i18n::RULE_N_SCHEMA_CHARACTER_SET" ruleDesc="i18n::RULE_D_SCHEMA_CHARACTER_SET" ruleTarget="Schema" scriptType="DetectRules"><![CDATA[
#define "require" as bool
        default "true"
        enum ["true", "false"]
        hint "强制要求设置字符集"
#define "character_set" as string
        default "utf8mb4"
        enum ["utf8", "utf8mb4"]
        hint "允许使用的字符集"

// 对于 alter 语句，只有当设置了 character set 选项时候才进行校验
if
  @domain.sqlType in ['ALTER_CATALOG'] and
  @func.string.isNotBlank(@domain.characterSet)
then

    if @func.string.isBlank(#{character_set}) then
      return false //规则配置错误
    else
      return @func.string.equalsIgnoreCase(@domain.characterSet, #{character_set})
    end

end

// 对于 create 语句，检测是否必须设置 character set 选项
if @domain.sqlType == 'CREATE_CATALOG' then

  if cast(#{require} as bool) then

    if @func.string.isBlank(#{character_set}) then
      return false //规则配置错误
    else
      return @func.string.equalsIgnoreCase(@domain.characterSet, #{character_set})
    end

  else

    if @func.string.isBlank(@domain.characterSet) then
      return true
    else
      return @func.string.equalsIgnoreCase(@domain.characterSet, #{character_set})
    end

  end

end
]]></ruleDef>
        <ruleDef id="rule_schema_002" ruleName="i18n::RULE_N_SCHEMA_COLLATE" ruleDesc="i18n::RULE_D_SCHEMA_COLLATE" ruleTarget="Schema" scriptType="DetectRules"><![CDATA[
#define "require" as bool
        default "true"
        enum ["true", "false"]
        hint "强制要求设置排序规则"
#define "collate" as string
        default "utf8mb4_unicode_ci"
        enum ["utf8_unicode_ci", "utf8mb4_unicode_ci"]
        hint "允许使用的排序规则"

// 对于 alter 语句，只有当设置了 collate 选项时候才进行校验
if
  @domain.sqlType in ['ALTER_CATALOG'] and
  @func.string.isNotBlank(@domain.collate)
then

    if @func.string.isBlank(#{collate}) then
      return false //规则配置错误
    else
      return @func.string.equalsIgnoreCase(@domain.collate, #{collate})
    end

end

// 对于 create 语句，检测是否必须设置 collate 选项
if @domain.sqlType == 'CREATE_CATALOG' then

  if cast(#{require} as bool) then

    if @func.string.isBlank(#{collate}) then
      return false //规则配置错误
    else
      return @func.string.equalsIgnoreCase(@domain.collate, #{collate})
    end

  else

    if @func.string.isBlank(@domain.collate) then
      return true
    else
      return @func.string.equalsIgnoreCase(@domain.collate, #{collate})
    end

  end

end
]]></ruleDef>
        <ruleDef id="rule_schema_003" ruleName="i18n::RULE_N_SCHEMA_NAME_CASE_TYPE" ruleDesc="i18n::RULE_D_SCHEMA_NAME_CASE_TYPE" ruleTarget="Schema" scriptType="DetectRules"><![CDATA[
#define "caseType" as string
        default "Lower case"
        enum ["Lower case", "Upper case", "Lower camel case", "Upper camel case"]
        hint "名称拼写规则"

if @domain.sqlType == 'CREATE_SCHEMA' then
  checkName = @domain.schema
elseif @domain.sqlType == 'RENAME_SCHEMA' then
  checkName = @domain.newName
else
  return true
end

// ref document https://newbedev.com/regex-for-pascalcased-words-aka-camelcased-with-leading-uppercase-letter

if #{caseType} == 'Lower case' then
  return @func.string.lowerCase(checkName) == checkName

elseif #{caseType} == 'Upper case' then

  return @func.string.upperCase(checkName) == checkName

elseif #{caseType} == 'Lower camel case' then
  return checkName matches '[a-z]+((\d)|([A-Z0-9][a-z0-9]+))*([A-Z])?'

elseif #{caseType} == 'Upper camel case' then
  return checkName matches '([A-Z][a-z0-9]+)((\d)|([A-Z0-9][a-z0-9]+))*([A-Z])?'

else

  return false
end
]]></ruleDef>
        <ruleDef id="rule_schema_004" ruleName="i18n::RULE_N_SCHEMA_REDIS_COMMAND_CHECK" ruleDesc="i18n::RULE_D_SCHEMA_REDIS_COMMAND_CHECK" ruleTarget="" scriptType="DetectRules"><![CDATA[
#define "checkMode" as string
        default "Allow"
        enum ["Allow", "Reject"]
        hint "名单规则"
#define "commands" as string
        default ""
        hint "名单中的命令，多条使用分号分隔"

if @domain.dsType != 'Redis' then
  return true
end

if #{checkMode} === 'Allow' then
  return @domain.command in
         @func.string.split(@func.string.upperCase(#{commands}),';')
elseif #{checkMode} === 'Reject' then
  return @domain.command not in
         @func.string.split(@func.string.upperCase(#{commands}),';')
else
  return true
end
]]></ruleDef>
        <ruleDef id="rule_schema_005" ruleName="i18n::RULE_N_SCHEMA_MONGO_COMMAND_CHECK" ruleDesc="i18n::RULE_D_SCHEMA_MONGO_COMMAND_CHECK" ruleTarget="" scriptType="DetectRules"><![CDATA[
#define "checkMode" as string
        default "Allow"
        enum ["Allow", "Reject"]
        hint "名单规则"
#define "functions" as string
        default ""
        hint "名单中的方法，通配符多条使用分号分隔"

if @domain.dsType != 'MongoDB' then
  return true
end

if #{checkMode} === 'Allow' then
  return @domain.func in
         @func.string.split(#{functions},';')
elseif #{checkMode} === 'Reject' then
  return @domain.func not in
         @func.string.split(#{functions},';')
else
  return true
end

]]></ruleDef>

        <!-- table -->
        <ruleDef id="rule_table_001" ruleName="i18n::RULE_N_TABLE_AUTO_INCREMENT" ruleDesc="i18n::RULE_D_TABLE_AUTO_INCREMENT" ruleTarget="Table" scriptType="DetectRules" oldId="3"><![CDATA[
#define "require" as bool
        default "false"
        enum ["true", "false"]
        hint "强制要求设置自增初始值"
#define "number" as int
        default "1"
        hint "建表自增初始值"

if @domain.sqlType != 'CREATE_TABLE' then
  return true
end

if @func.string.isBlank(@domain.autoIncrement) then

  return !cast(#{require} as bool)

else

  if @func.string.isBlank(#{number}) then
    return false // 规则配置错误
  else
    return cast(@domain.autoIncrement as int) == cast(#{number} as int)
  end

end
]]></ruleDef>
        <ruleDef id="rule_table_002" ruleName="i18n::RULE_N_TABLE_CREATE_MAX_COLUMNS" ruleDesc="i18n::RULE_D_TABLE_CREATE_MAX_COLUMNS" ruleTarget="Table" scriptType="DetectRules" oldId="4"><![CDATA[
#define "maxCount" as int
        default "50"
        hint "表最大字段数量"

if
  @domain.sqlType != 'CREATE_TABLE'
then
  return true
end

return @func.array.size(@domain.columns) <= cast(#{maxCount} as int)
